# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1128, 889)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 140, 1071, 681))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_card = QtGui.QWidget()
        self.page_card.setObjectName(_fromUtf8("page_card"))
        self.listWidget = QtGui.QListWidget(self.page_card)
        self.listWidget.setGeometry(QtCore.QRect(480, 110, 521, 471))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.pushButton_set_card = QtGui.QPushButton(self.page_card)
        self.pushButton_set_card.setGeometry(QtCore.QRect(480, 44, 281, 51))
        self.pushButton_set_card.setObjectName(_fromUtf8("pushButton_set_card"))
        self.label = QtGui.QLabel(self.page_card)
        self.label.setGeometry(QtCore.QRect(0, 230, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.lcdNumber = QtGui.QLCDNumber(self.page_card)
        self.lcdNumber.setGeometry(QtCore.QRect(190, 230, 201, 41))
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.lcdNumber_2 = QtGui.QLCDNumber(self.page_card)
        self.lcdNumber_2.setGeometry(QtCore.QRect(10, 140, 381, 41))
        self.lcdNumber_2.setSmallDecimalPoint(False)
        self.lcdNumber_2.setNumDigits(16)
        self.lcdNumber_2.setDigitCount(16)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.label_2 = QtGui.QLabel(self.page_card)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.toolButton_refresh = QtGui.QToolButton(self.page_card)
        self.toolButton_refresh.setGeometry(QtCore.QRect(790, 40, 201, 51))
        self.toolButton_refresh.setObjectName(_fromUtf8("toolButton_refresh"))
        self.pushButton_add_card = QtGui.QPushButton(self.page_card)
        self.pushButton_add_card.setGeometry(QtCore.QRect(480, 604, 331, 51))
        self.pushButton_add_card.setObjectName(_fromUtf8("pushButton_add_card"))
        self.stackedWidget.addWidget(self.page_card)
        self.page_add_card = QtGui.QWidget()
        self.page_add_card.setObjectName(_fromUtf8("page_add_card"))
        self.stackedWidget.addWidget(self.page_add_card)
        self.page_top_up_card = QtGui.QWidget()
        self.page_top_up_card.setObjectName(_fromUtf8("page_top_up_card"))
        self.pushButton_top_up_card = QtGui.QPushButton(self.page_top_up_card)
        self.pushButton_top_up_card.setGeometry(QtCore.QRect(80, 230, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_top_up_card.setFont(font)
        self.pushButton_top_up_card.setObjectName(_fromUtf8("pushButton_top_up_card"))
        self.label_15 = QtGui.QLabel(self.page_top_up_card)
        self.label_15.setGeometry(QtCore.QRect(30, 280, 53, 14))
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.page_top_up_card)
        self.label_16.setGeometry(QtCore.QRect(80, 40, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.lineEdit_top_up_card = QtGui.QLineEdit(self.page_top_up_card)
        self.lineEdit_top_up_card.setGeometry(QtCore.QRect(80, 130, 341, 41))
        self.lineEdit_top_up_card.setObjectName(_fromUtf8("lineEdit_top_up_card"))
        self.stackedWidget.addWidget(self.page_top_up_card)
        self.page_2_transaction = QtGui.QWidget()
        self.page_2_transaction.setObjectName(_fromUtf8("page_2_transaction"))
        self.label_17 = QtGui.QLabel(self.page_2_transaction)
        self.label_17.setGeometry(QtCore.QRect(60, 40, 781, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.lineEdit = QtGui.QLineEdit(self.page_2_transaction)
        self.lineEdit.setGeometry(QtCore.QRect(60, 130, 501, 51))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_18 = QtGui.QLabel(self.page_2_transaction)
        self.label_18.setGeometry(QtCore.QRect(60, 220, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lineEdit_2 = QtGui.QLineEdit(self.page_2_transaction)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 300, 421, 51))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pushButton_trans = QtGui.QPushButton(self.page_2_transaction)
        self.pushButton_trans.setGeometry(QtCore.QRect(60, 410, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_trans.setFont(font)
        self.pushButton_trans.setObjectName(_fromUtf8("pushButton_trans"))
        self.stackedWidget.addWidget(self.page_2_transaction)
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 10, 1001, 111))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.toolButton_card = QtGui.QToolButton(self.horizontalLayoutWidget)
        self.toolButton_card.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_card.sizePolicy().hasHeightForWidth())
        self.toolButton_card.setSizePolicy(sizePolicy)
        self.toolButton_card.setMinimumSize(QtCore.QSize(47, 20))
        self.toolButton_card.setCheckable(True)
        self.toolButton_card.setAutoExclusive(True)
        self.toolButton_card.setObjectName(_fromUtf8("toolButton_card"))
        self.horizontalLayout.addWidget(self.toolButton_card)
        self.toolButton_top_up = QtGui.QToolButton(self.horizontalLayoutWidget)
        self.toolButton_top_up.setCheckable(True)
        self.toolButton_top_up.setAutoExclusive(True)
        self.toolButton_top_up.setObjectName(_fromUtf8("toolButton_top_up"))
        self.horizontalLayout.addWidget(self.toolButton_top_up)
        self.toolButton_transaction = QtGui.QToolButton(self.horizontalLayoutWidget)
        self.toolButton_transaction.setCheckable(True)
        self.toolButton_transaction.setAutoExclusive(True)
        self.toolButton_transaction.setObjectName(_fromUtf8("toolButton_transaction"))
        self.horizontalLayout.addWidget(self.toolButton_transaction)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1128, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton_set_card.setText(_translate("MainWindow", "Выбрать карту", None))
        self.label.setText(_translate("MainWindow", "На счету:", None))
        self.label_2.setText(_translate("MainWindow", "Номер карты:", None))
        self.toolButton_refresh.setText(_translate("MainWindow", "Обновить", None))
        self.pushButton_add_card.setText(_translate("MainWindow", "Добавить карту", None))
        self.pushButton_top_up_card.setText(_translate("MainWindow", "Пополнить", None))
        self.label_16.setText(_translate("MainWindow", "Укажите сумму:", None))
        self.label_17.setText(_translate("MainWindow", "Номер карты получателя:", None))
        self.label_18.setText(_translate("MainWindow", "Сумма:", None))
        self.pushButton_trans.setText(_translate("MainWindow", "Перевести", None))
        self.toolButton_card.setText(_translate("MainWindow", "Карта", None))
        self.toolButton_top_up.setText(_translate("MainWindow", "Пополнить карту", None))
        self.toolButton_transaction.setText(_translate("MainWindow", "Перевести на карту", None))

